%YAML 1.1
---
id: asdf://dkist.nso.edu/manifests/dkist-1.7.0
extension_uri: asdf://dkist.nso.edu/dkist/extensions/dkist-1.7.0
title: DKIST extension
description: ASDF schemas and tags for DKIST classes.

tags:
  - schema_uri: "asdf://dkist.nso.edu/schemas/file_manager-1.1.0"
    tag_uri: "asdf://dkist.nso.edu/tags/file_manager-1.1.0"
  - schema_uri: "asdf://dkist.nso.edu/schemas/dataset-1.3.0"
    tag_uri: "asdf://dkist.nso.edu/tags/dataset-1.3.0"
  - schema_uri: "asdf://dkist.nso.edu/schemas/tiled_dataset-1.4.0"
    tag_uri: "asdf://dkist.nso.edu/tags/tiled_dataset-1.4.0"
  - schema_uri: "asdf://dkist.nso.edu/schemas/inversion-0.1.0"
    tag_uri: "asdf://dkist.nso.edu/tags/inversion-0.1.0"
  - schema_uri: "asdf://dkist.nso.edu/schemas/profiles-0.1.0"
    tag_uri: "asdf://dkist.nso.edu/tags/profiles-0.1.0"
